/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "REST APIs with Flask and Python",
  "tagline": "Build and deploy REST APIs using Flask, PostgreSQL, and Docker",
  "url": "https://rest-apis-flask.teclado.com",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "tecladocode",
  "projectName": "rest-apis-flask-python",
  "scripts": [
    {
      "src": "https://plau-prox.teclado.workers.dev/get/script.outbound-links.js",
      "defer": true,
      "data-domain": "rest-apis-flask.teclado.com",
      "data-api": "https://plau-prox.teclado.workers.dev/send/event"
    }
  ],
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "sidebarPath": "C:\\Users\\lpsin\\area52\\RestAPI\\RestAPI_code\\00_book\\sidebars.js",
          "exclude": [
            "**/start/**",
            "**/end/**"
          ],
          "editUrl": "https://github.com/tecladocode/rest-apis-flask-python/tree/develop/docs/"
        },
        "theme": {
          "customCss": "C:\\Users\\lpsin\\area52\\RestAPI\\RestAPI_code\\00_book\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "algolia": {
      "appId": "1BEGBIP9SH",
      "apiKey": "882167549d623413f9b5314788a0d900",
      "indexName": "docusaurus-2",
      "searchParameters": {},
      "searchPagePath": "search",
      "contextualSearch": true
    },
    "navbar": {
      "title": "REST APIs with Flask and Python",
      "logo": {
        "alt": "Teclado Logo",
        "src": "img/favicon.ico"
      },
      "items": [
        {
          "type": "doc",
          "docId": "course_intro/intro",
          "position": "left",
          "label": "Tutorial"
        },
        {
          "href": "/insomnia-files/",
          "position": "left",
          "label": "Insomnia files"
        },
        {
          "href": "https://go.tecla.do/rest-apis-ebook",
          "label": "Get the course",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "announcementBar": {
      "id": "support_us",
      "content": "<span style=\"font-weight: 600\">Unlock all video lessons and support us by <a target=\"_blank\" style=\"background-color: #ff7d82; background-image: linear-gradient(90deg, #FF7D82, #50e3c2); background-clip: text; color: transparent; -webkit-background-clip: text; -moz-background-clip: text; -webkit-text-fill-color: transparent; -moz-text-fill-color: transparent; \" rel=\"noopener noreferrer\" href=\"https://go.tecla.do/rest-apis-ebook\">buying the course</a>!</span>",
      "backgroundColor": "#1c2023",
      "textColor": "#fff",
      "isCloseable": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Learn",
          "items": [
            {
              "href": "https://go.tecla.do/rest-apis-ebook",
              "label": "Get the course"
            },
            {
              "label": "Tutorial",
              "to": "/docs/course_intro/"
            }
          ]
        },
        {
          "title": "Social",
          "items": [
            {
              "label": "Discord",
              "href": "https://go.tecla.do/discord"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/jslvtr"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/tecladocode/rest-apis-flask-python"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Teclado Ltd. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#f8f8f2",
          "backgroundColor": "#272822"
        },
        "styles": [
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(162, 191, 252)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "#f92672",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "inserted"
            ],
            "style": {
              "color": "rgb(173, 219, 103)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "#8292a2",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "url"
            ],
            "style": {
              "color": "#a6e22e"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "#f8f8f2"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "#ae81ff"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function",
              "class-name"
            ],
            "style": {
              "color": "#e6db74"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "style": {
              "color": "#f8f8f2"
            }
          },
          {
            "types": [
              "selector",
              "doctype"
            ],
            "style": {
              "color": "#a6e22e",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "tag",
              "operator",
              "keyword"
            ],
            "style": {
              "color": "#66d9ef"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "#ae81ff"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)",
              "opacity": 0.7
            }
          },
          {
            "types": [
              "tag",
              "property"
            ],
            "style": {
              "color": "#f92672"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "#a6e22e !important"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "#8292a2"
            }
          },
          {
            "types": [
              "rule"
            ],
            "style": {
              "color": "#e6db74"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "docker"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
